# Generated by Django 4.1.2 on 2022-11-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city_of_residence',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city_of_residence2',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=125, null=True, verbose_name='country')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='district')),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='zip_code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
