# Generated by Django 4.1.2 on 2022-11-03 14:19

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[users.validators.PhoneValidator()]),
        ),
    ]
