# Generated by Django 4.1.2 on 2022-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
