# Generated by Django 4.1.2 on 2022-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='product',
            field=models.ManyToManyField(related_name='profiles', to='shop.productmodel'),
        ),
    ]
