# Generated by Django 4.1.2 on 2022-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistorymodel',
            name='products',
            field=models.ManyToManyField(to='shop.productmodel'),
        ),
    ]
