# Generated by Django 4.1.2 on 2022-11-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('orders', '0002_alter_orderhistorymodel_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='product',
            field=models.ManyToManyField(to='shop.productmodel'),
        ),
    ]
