# Generated by Django 4.1.2 on 2022-11-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_orderhistorymodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistorymodel',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='orderhistorymodel',
            name='district',
        ),
        migrations.AddField(
            model_name='orderhistorymodel',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='address1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='country',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
